version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
          RAKE_ENV: test

      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: marketing_test
          POSTGRES_PASSWORD: ""

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler -v 2.0.2

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --no-deployment --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load RAILS_ENV=test

      # run lints
      - run:
          name: run rubocop
          command: bundle exec rubocop

      - run:
          name: run scss int
          command: bundle exec scss-lint app/assets/stylesheets/

      - run: yarn
      - run: bundle exec rails webpacker:compile

      # run tests!
      - run:
          name: run tests
          command: bundle exec rails test

      # run tests!
      - run:
          name: run system test
          command: bundle exec rails test:system
